# Generated by Django 5.1.1 on 2024-09-25 14:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehículo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Ford', max_length=20, verbose_name='marca vehículo')),
                ('modelo', models.CharField(max_length=100, verbose_name='modelo vehículo')),
                ('carrocería', models.CharField(max_length=100, unique=True, verbose_name='serial de carrocería')),
                ('motor', models.CharField(max_length=50, unique=True, verbose_name='serial de motor')),
                ('categoría', models.CharField(choices=[('P', 'Particular'), ('T', 'Transporte'), ('C', 'Carga')], default='Particular', max_length=20, verbose_name='categoría vehículo')),
                ('precio', models.PositiveIntegerField(help_text='values between 0 and %(limit_value)s', validators=[django.core.validators.MaxValueValidator(500000000, message='value must be less than %(limit_value)s')], verbose_name='precio vehículo')),
                ('creación', models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 21, 41, 588304, tzinfo=datetime.timezone.utc), verbose_name='fecha creación')),
                ('modificación', models.DateTimeField(default=datetime.datetime(2024, 9, 25, 14, 21, 41, 588304, tzinfo=datetime.timezone.utc), verbose_name='fecha modificación')),
            ],
        ),
    ]
