# Generated by Django 5.1.1 on 2024-09-25 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='creación',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha creación'),
        ),
        migrations.AlterField(
            model_name='vehículo',
            name='modificación',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha modificación'),
        ),
    ]
