# Generated by Django 5.1.1 on 2024-09-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehículo_options_alter_vehículo_creación_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='creación',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha creación'),
        ),
        migrations.AlterField(
            model_name='vehículo',
            name='modificación',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha modificación'),
        ),
    ]
