# Generated by Django 5.1.1 on 2024-09-26 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehículo_creación_alter_vehículo_modificación'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='precio',
            field=models.PositiveIntegerField(help_text='values between 0 and 500_000', validators=[django.core.validators.MaxValueValidator(500000)], verbose_name='precio vehículo'),
        ),
    ]
