# Generated by Django 5.1.1 on 2024-09-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_alter_vehículo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='marca',
            field=models.CharField(choices=[('1', 'Chevrolet'), ('2', 'Fiat'), ('3', 'Ford'), ('4', 'Toyota')], default='Fiat', max_length=20, verbose_name='marca vehículo'),
        ),
    ]
