# Generated by Django 5.1.1 on 2024-10-02 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0011_alter_vehículo_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehículoGalería',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imágenes', models.ImageField(help_text='archivo jpg o png', upload_to='uploads/vehículo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='imágenes vehículo')),
                ('vehículo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehículo')),
            ],
        ),
    ]
