# Generated by Django 5.1.1 on 2024-10-03 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0014_alter_vehículogalería_imágenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículogalería',
            name='imágenes',
            field=models.ImageField(help_text='archivo jpg o png', upload_to='vehículo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', '.webp'], message='solo archivos de imágenes')], verbose_name='imágenes vehículo'),
        ),
    ]
