# Generated by Django 5.1.1 on 2024-10-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0019_alter_vehículogalería_imágenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículogalería',
            name='descripción',
            field=models.CharField(error_messages='solo hasta 80 caracteres', max_length=80, verbose_name='descripción imagen'),
        ),
    ]
