# Generated by Django 5.1.1 on 2024-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0020_alter_vehículogalería_descripción'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículogalería',
            name='descripción',
            field=models.CharField(error_messages='solo hasta 150 caracteres', max_length=150, verbose_name='descripción imagen'),
        ),
    ]
