# Generated by Django 5.1.1 on 2024-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0021_alter_vehículogalería_descripción'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='marca',
            field=models.CharField(default='Ford', max_length=20, verbose_name='marca vehículo'),
        ),
    ]
