# Generated by Django 5.1.1 on 2024-10-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0023_alter_vehículo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='marca',
            field=models.CharField(max_length=40, verbose_name='marca vehículo'),
        ),
    ]
