# Generated by Django 5.1.1 on 2024-10-08 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0024_alter_vehículo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículo',
            name='precio',
            field=models.PositiveIntegerField(help_text='precios entre 0 a 500.000', validators=[django.core.validators.MaxValueValidator(500000, message='valor debe ser menor o igual a %(limit_value)s')], verbose_name='precio vehículo'),
        ),
    ]
