# Generated by Django 5.1.1 on 2024-10-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0025_alter_vehículo_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehículo',
            options={'permissions': [('visualizar_catalogo', 'Puede ver la lista de vehículos disponibles'), ('descargar_tabla', 'Puede descargar la lista de vehículos')]},
        ),
    ]
