# Generated by Django 5.1.1 on 2024-10-09 19:11

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0026_alter_vehículo_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehículo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('carrocería'), django.db.models.functions.text.Upper('motor'), name='unique uppercase'),
        ),
    ]
