# Generated by Django 5.1.1 on 2024-10-09 19:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0028_remove_vehículo_unique_uppercase_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehículo',
            name='unique uppercase',
        ),
        migrations.AddConstraint(
            model_name='vehículo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('carrocería'), name='unique uppercase', violation_error_message='esta valor ya existe'),
        ),
    ]
