# Generated by Django 5.1.1 on 2024-10-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0031_remove_vehículo_unique_uppercase_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehículo',
            name='unique uppercase',
        ),
    ]
