# Generated by Django 5.1.1 on 2024-10-10 13:32

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0032_remove_vehículo_unique_uppercase'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehículo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('carrocería'), name='unique upper', violation_error_message='serial no es única'),
        ),
    ]
