# Generated by Django 5.1.1 on 2024-10-10 13:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0033_vehículo_unique_upper'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehículo',
            name='unique upper',
        ),
        migrations.AddConstraint(
            model_name='vehículo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('carrocería'), name='unique carrocería upper', violation_error_message='la serial que intenta ingresar ya existe'),
        ),
    ]
