# Generated by Django 5.1.1 on 2024-10-10 13:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0034_remove_vehículo_unique_upper_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehículo',
            name='unique carrocería upper',
        ),
        migrations.AddConstraint(
            model_name='vehículo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('carrocería'), name='unique carrocería upper', violation_error_message='la serial de carrocería que intenta ingresar ya existe'),
        ),
        migrations.AddConstraint(
            model_name='vehículo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('motor'), name='unique motor upper', violation_error_message='la serial de motor que intenta ingresar ya existe'),
        ),
    ]
