# Generated by Django 5.1.1 on 2024-10-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0036_remove_vehículo_unique_carrocería_upper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehículogalería',
            name='vehículo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehículos', to='vehiculo.vehículo'),
        ),
    ]
